### ISSUE TITLE
first character of lines cut off

### ISSUE THREAD

**Issue by MichaelLSmith** [jsbin/jsbin#2638]
I have a problem with having the first character being cutoff in the javascript screen. I have line numbering on. It's like there needs to be scroll bar at the bottom to move the screen to the right. It's shown on the first line. This happens frequently. I tried re-freshing, but it doesn't fix it.
![screencutoff](https://cloud.githubusercontent.com/assets/11539693/11461154/5e2fb014-96cb-11e5-9ef2-e442521d74f0.png)

**Comment by remy** [comment]
Can you replicate in an incognito window? I see you have a lot of browser plugins that could be at play too.

**Comment by abhisekp** [comment]
@remy this is not a reproducible problem.

I've also had this problem many time. But a simple refresh solves the issue.

Most likely this might be a CodeMirror bug maybe?

**Comment by remy** [comment]
@abhisekp it's possibly a lot of these CM related bugs have been closed in the update I pushed last week (it's now on 5.17.1, whereas before it was on 5.3.0).

**Comment by abhisekp** [comment]
@remy nope! Not fixed. Also i'm not sure if this is a CM bug ...
I had fell into this bug just minutes ago and also yesterday.

**Comment by remy** [comment]
@abhisekp can you you replicate - or submit a PR to fix the CSS?
