### ISSUE TITLE
Theme resetted

### ISSUE THREAD

**Issue by caub** [jsbin/jsbin#2834]
I had a dark theme set up since months, and today, without changing anything I have:

![image](https://cloud.githubusercontent.com/assets/3134574/17405533/2b4e6b1e-5a60-11e6-9cef-031341100149.png)

the syntax coloration is quite hard to read now, I don't know if it's a bug or a new theme/design

**Comment by naknode** [comment]
Same here. I have had monokai for months and my theme is now complete a white page. I keep changing themes but nothing.

**Comment by remy** [comment]
I release a new version of CodeMirror last night, so it's likely that the theme got lost then.

I'll check and report back here.

**Comment by remy** [comment]
Fixed last night. Thanks folks.

**Comment by naknode** [comment]
Changing themes still does not work for me. I have tried incognito, new browser, etc.
