### ISSUE TITLE
Editor settings and preferences don't work

### ISSUE THREAD

**Issue by flavius1102** [jsbin/jsbin#3283]
Hi, I tried to enter Editor settings in Account but it doesn't open. It says error, too many redirects. What can I do now? Thank you!

**Comment by NikolayOskin** [comment]
same issue
Google Chrome, private mode and usual mode

**Comment by alexandrudinca1602** [comment]
I have the same problem with safari

**Comment by djneils** [comment]
same problem here! please help!! (chrome)

**Comment by mickelj** [comment]
Ditto here.  Thanks!

**Comment by cs-marton** [comment]
same here

**Comment by danywalls** [comment]
same here!

**Comment by francmarrara** [comment]
same here!

**Comment by evelynweston** [comment]
same here!

**Comment by remy** [comment]
Firstly…please don't do the whole "same here" thing, it's not useful… a PR would be! 

Anyway, there's odd behaviour here, _some_ account pages work, but most do the redirect loop:

- https://jsbin.com/account/editor
- https://jsbin.com/account/preferences
- https://jsbin.com/account/embed
- https://jsbin.com/account/assets
- https://jsbin.com/account/delete

All of these go into a redirect loop, I've noticed specifically it redirects from http to https and back again. It makes no sense as to why it would redirect to http, but once on http, it's _correctly_ redirecting to https.

It's also odd that the /subscription and /profile page don't run the redirect loop.

I half suspect a misconfiguration in the nginx setup, but equally there could be something in the code that's the issue. The oddest part is the code base hasn't changed in a long while, so it's very strange that this has started happening.

My next action: to review any commits since the issue was opened.

**Comment by remy** [comment]
More digging. It looks like the ssl option flag is being set to `false` (I'm guessing when it was turned on by default, the option was missing from the page so saving prefs then caused the flag to flip to `false`).

Now it seems (but I'm trying to verify) that once a browser visits https it'll never load http again. To test, visit https://jsbin.com (signed out), and then try to load the http version - it'll redirect. This isn't behaviour that jsbin has built, but _I believe_ is happening inside the browser. This is new behaviour which is exposing this redirect issue.

**Comment by remy** [comment]
Fixed. A bit of a sledgehammer approach, but it's working. All pages under /account are now forced on to SSL. 

I suspect this'll have a side effect, but I'll deal with that fire once it reaches my front door…

**Comment by flavius1102** [comment]
Remy, thank you very much for your help! I really appreciate it!

**Comment by Richie765** [comment]
@remy, could it be that this change wasn't pushed to github? I'm still having the same issue and I can't find a commit related to this.
